title: Waleedev
tagline: Full-Stack Developer expertise in React, Vite, TypeScript, Tailwind CSS, Golang, SQL, Python, Cloudflare, Git, Github
description: Portfolio of Waleed showcasing projects in React Vite TypeScript Tailwind Golang SQL Python and Cloudflare.

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
